name = "lisaany"
main = "src/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
PRICE_SELF_PACED_MONTHLY = "price_1TVwYmRpquEfxb9t1DQDAgRE"
PRICE_WITH_TUTOR_MONTHLY = "price_1TVwcgRpquEfxb9tuJYp47Ui"
PRICE_WITH_TUTOR_YEARLY = "price_1TVwcgRpquEfxb9tWbqNnwwP"
SUPABASE_URL = "https://cfaxrzfqvoalwznkhwnx.supabase.co"

# force rebuild 2026-05-12
