name = "lisaany"
main = "src/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

# Serve your HTML files (in the repo root) as static assets.
# Requests not matching /api/* will be served as static files.
[assets]
directory = "./"
binding = "ASSETS"
not_found_handling = "single-page-application"




